### ISSUE TITLE
Create user page

### ISSUE THREAD

**Issue by Lazalatin** [Xexanos/LibreCarSharing#7]
This page should contain:

- user information to view and edit
- messages to and from users to view and edit
- blockings to view and edit

**Comment by Xexanos** [comment]
I would like to postpone the messaging part. Eventually I would recommend to create a separate page for that.

**Comment by Lazalatin** [comment]
Should we put that into backlog or implement the messaging part as a seperate page?
@freddy41 @Xexanos
